"""update schema

Revision ID: 015ecec93efb
Revises: 89c14294ba16
Create Date: 2022-05-26 11:53:44.177727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015ecec93efb'
down_revision = '89c14294ba16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('userInput', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('adder', sa.Integer(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('others', sa.Text(), nullable=True),
    sa.Column('sizes', sa.String(length=225), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('orderNumber', sa.String(length=10), nullable=True),
    sa.Column('waitTime', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientvisited',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('serviceId', sa.Integer(), nullable=True),
    sa.Column('userInput', sa.String(length=30), nullable=True),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.Column('workerId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('addressOne', sa.String(length=50), nullable=True),
    sa.Column('addressTwo', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('postalcode', sa.String(length=7), nullable=True),
    sa.Column('phonenumber', sa.String(length=10), nullable=True),
    sa.Column('logo', sa.String(length=70), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('owners', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('hours', sa.String(length=710), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phonenumber')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('parentMenuId', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cellnumber', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=110), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('profile', sa.String(length=70), nullable=True),
    sa.Column('hours', sa.Text(), nullable=True),
    sa.Column('info', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellnumber'),
    sa.UniqueConstraint('password')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('menuId', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=70), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('others', sa.Text(), nullable=True),
    sa.Column('sizes', sa.String(length=150), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('workerId', sa.Integer(), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('menuId', sa.Text(), nullable=True),
    sa.Column('serviceId', sa.Integer(), nullable=True),
    sa.Column('userInput', sa.String(length=30), nullable=True),
    sa.Column('time', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('cancelReason', sa.String(length=200), nullable=True),
    sa.Column('locationType', sa.String(length=15), nullable=True),
    sa.Column('customers', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=225), nullable=True),
    sa.Column('orders', sa.Text(), nullable=True),
    sa.Column('table', sa.String(length=20), nullable=True),
    sa.Column('info', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('menuId', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=70), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cellnumber', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=110), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('info', sa.String(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellnumber'),
    sa.UniqueConstraint('password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('service')
    op.drop_table('schedule')
    op.drop_table('product')
    op.drop_table('owner')
    op.drop_table('menu')
    op.drop_table('location')
    op.drop_table('clientvisited')
    op.drop_table('cart')
    # ### end Alembic commands ###
