"""update schema

Revision ID: 12c4b67c87bf
Revises: 34c002edbca6
Create Date: 2021-07-21 21:54:30.359885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c4b67c87bf'
down_revision = '34c002edbca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('seaters', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'seaters')
    # ### end Alembic commands ###
