"""update schema

Revision ID: 34c002edbca6
Revises: 
Create Date: 2021-07-21 17:37:38.107027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34c002edbca6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('menuId', sa.Text(), nullable=True),
    sa.Column('serviceId', sa.Text(), nullable=True),
    sa.Column('time', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('cancelReason', sa.String(length=200), nullable=True),
    sa.Column('nextTime', sa.String(length=15), nullable=True),
    sa.Column('locationType', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('appointment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('locationId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('menuId', mysql.TEXT(), nullable=True),
    sa.Column('serviceId', mysql.TEXT(), nullable=True),
    sa.Column('time', mysql.TEXT(), nullable=True),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('cancelReason', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('nextTime', mysql.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('schedule')
    # ### end Alembic commands ###
