"""update schema

Revision ID: 36207797652d
Revises: a4be28a76f6f
Create Date: 2021-07-20 17:25:44.984741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36207797652d'
down_revision = 'a4be28a76f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('time', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'time')
    # ### end Alembic commands ###
