"""update schema

Revision ID: 89c14294ba16
Revises: 
Create Date: 2022-05-26 10:35:54.518543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89c14294ba16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    op.drop_index('cellnumber', table_name='user')
    op.drop_index('password', table_name='user')
    op.drop_table('user')
    op.drop_table('cart')
    op.drop_index('phonenumber', table_name='location')
    op.drop_table('location')
    op.drop_table('product')
    op.drop_table('menu')
    op.drop_index('cellnumber', table_name='owner')
    op.drop_index('password', table_name='owner')
    op.drop_table('owner')
    op.drop_table('schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workerId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('locationId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('menuId', mysql.TEXT(), nullable=True),
    sa.Column('serviceId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userInput', mysql.TEXT(), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('cancelReason', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('locationType', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('customers', mysql.TEXT(), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('orders', mysql.TEXT(), nullable=True),
    sa.Column('table', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('owner',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cellnumber', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=110), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('profile', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('hours', mysql.TEXT(), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('password', 'owner', ['password'], unique=False)
    op.create_index('cellnumber', 'owner', ['cellnumber'], unique=False)
    op.create_table('menu',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('locationId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parentMenuId', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('product',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('locationId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('menuId', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('options', mysql.TEXT(), nullable=True),
    sa.Column('others', mysql.TEXT(), nullable=True),
    sa.Column('sizes', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('location',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('addressOne', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('addressTwo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('province', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('postalcode', mysql.VARCHAR(length=7), nullable=True),
    sa.Column('phonenumber', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('longitude', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('latitude', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('owners', mysql.TEXT(), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('hours', mysql.TEXT(), nullable=True),
    sa.Column('info', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('phonenumber', 'location', ['phonenumber'], unique=False)
    op.create_table('cart',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('locationId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userInput', mysql.TEXT(), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('adder', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('options', mysql.TEXT(), nullable=True),
    sa.Column('others', mysql.TEXT(), nullable=True),
    sa.Column('sizes', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('orderNumber', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('waitTime', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cellnumber', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=110), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('password', 'user', ['password'], unique=False)
    op.create_index('cellnumber', 'user', ['cellnumber'], unique=False)
    op.create_table('service',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('locationId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('menuId', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
