"""update schema

Revision ID: eaa94ddb0576
Revises: 1dc7b41aa882
Create Date: 2021-07-19 22:48:59.390122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa94ddb0576'
down_revision = '1dc7b41aa882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('cancelReason', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'cancelReason')
    # ### end Alembic commands ###
