"""update schema

Revision ID: f00739632e8b
Revises: 015ecec93efb
Create Date: 2022-05-26 13:00:50.152105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f00739632e8b'
down_revision = '015ecec93efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'info',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=720),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'info',
               existing_type=sa.String(length=720),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
