"""update schema

Revision ID: f8c75e79d87b
Revises: 36ea6f260b3d
Create Date: 2022-05-26 14:14:25.554742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8c75e79d87b'
down_revision = '36ea6f260b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'userInput',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=70),
               existing_nullable=True)
    op.alter_column('clientvisited', 'userInput',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=70),
               existing_nullable=True)
    op.alter_column('schedule', 'userInput',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=70),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'userInput',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('clientvisited', 'userInput',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('cart', 'userInput',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
