"""update schema

Revision ID: ff864169b34f
Revises: eaa94ddb0576
Create Date: 2021-07-19 23:57:03.132616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff864169b34f'
down_revision = 'eaa94ddb0576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('nextTime', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'nextTime')
    # ### end Alembic commands ###
